<fieldset class="form-list">
   <?php $_code=$this->getMethodCode() ?>

   <?php if(count($this->displayInstallments()) > 1){ ?>
	
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_installments"><?php echo $this->__('Installments') ?></label><br />
                <select id="<?php echo $_code ?>_cc_installments" name="cc_installments">
                
				<?php $_ccInstallments = $this->getInfoData('cc_installments') ?>
                
				<?php foreach ($this->displayInstallments() as $_allInstallments): ?>
				<?php foreach ($_allInstallments as $_installmentsCode => $_installmentsName): ?>
                    
					<option value="<?php echo $_installmentsCode ?>"<?php if($_installmentsCode==$_ccInstallments): ?> selected="selected"<?php endif ?>><?php echo $_installmentsName ?></option>
					
                <?php endforeach ?>
				<?php endforeach ?>
               
				</select>
            </div>
        </li>
    </ul>
   <?php } ?>
</fieldset>