allowed_parameters = {
	'IsPreAuth': bool,
	'ServiceId': int,
	'RequestLang': str,
	'FullName': str,
	'Email': str,
	'Phone': str,
	'Installments': int,
	'MaxInstallments': int,
	'MerchantTrns': str,
	'CustomerTrns': str,
	'SourceCode': str,
	'PaymentTimeOut': str,
	'ExpirationDate': str,
	'AllowRecurring': bool,
	'AllowsRecurring': bool,
	'Tags': list,
	'ActionUser': str,
	'DisableIVR': bool,
	'DisableCash': bool,
	'DisableCard': bool,
	'DisablePayAtHome': bool,
	'DisableExactAmount': bool
}